const searchSectionEl = document.querySelector("search-section")
const forecastSectionEl = document.querySelector("forecast-section")
const searchButtonEl = document.querySelector("search-button")
const clearHistoryEl = document.querySelector("clear-history")
const forecastItemEl = document.querySelector("forecast-item")
const searchHistoryListEl = document.querySelector("search-history-list")